### ISSUE TITLE
Replace Hex Viewer with WpfHexEditorControl

### ISSUE THREAD

**Issue by vector-man** [vector-man/IPS-Peek#3]
Replace the current hex viewer with 
WpfHexEditorControl: https://github.com/abbaye/WpfHexEditorControl

This will allow for more features and finally allow for an easier path to Thingy table support (it's built in to the control as a feature).

Currently, multiple highlight support now exists. A control swap should be easier now. I need to ensure all features are supported before I switch the control.

**Comment by abbaye** [comment]
Thank vector-man for use my work. I appreciate :smile:

**Comment by vector-man** [comment]
@abbaye No problem! Awesome work on the control! I'm also planning a general hex editor with it :).

**Comment by abbaye** [comment]
Super news :) I want to see your editor when you can

**Comment by vector-man** [comment]
Highlight support should now be able to support the control swap.

**Comment by vector-man** [comment]
Swapping the control caused some performance issues, because of the way IPS Peek highlights potentially thousands of values. For now, this is on hold until I can get similar performance from the swap.
